version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis-server-main
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: postgres-db-main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telehealth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

  app:
    build: .
    container_name: fastify-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db-main:5432/telehealth?schema=public
      - REDIS_URL=redis://redis:6379
      - PORT=3001
      - HOST=0.0.0.0
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - my_network
    restart: always

volumes:
  redis_data:
  postgres_data:

networks:
  my_network:
    driver: bridge
